<?xml version="1.0" encoding="utf-8"?><Database Name="TESTODBML" Class="TESTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-9ON3GB8;Initial Catalog=TESTODBML;User ID=sa;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TESTODBMLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TEST2" Member="TEST2s">
    <Type Name="TEST2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Program_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Start_Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Is_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="End_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TEST" Member="TESTs">
    <Type Name="TEST">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Program_Nmae" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Start_Date" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="Is_Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Created_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>